TempleDAO/temple

- apps/dapp/src/components/Layouts/CoreLayout/Header.tsx
- apps/dapp/src/components/Pages/Core/Trade/index.tsx
- apps/dapp/src/hooks/use-watch-asset.tsx
> Add temple token to wallet 

- apps/dapp/package.json
- yarn.lock
> Add missing dependency

- apps/dapp/src/components/Pages/Core/VaultPages/Stake.tsx
Removes depositing temple/ogTemple with faith options
> remove faith options from stake screen

- apps/dapp/src/components/Vault/utils.ts
> update precision when displaying Temple

- apps/core-subgraph/schema.graphql
- apps/core-subgraph/src/entities/vaultUserBalance.ts
- apps/core-subgraph/src/entities/withdraw.ts
- apps/core-subgraph/src/utils/constants.ts
Also fixes negative staked amounts.
> Add cumulative earned amount to vault user balances

- apps/dapp/src/components/Pages/Ascend/PoolList.tsx
- apps/dapp/src/components/Pages/Ascend/admin/edit.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/index.tsx
- apps/dapp/src/components/Pages/Ascend/hooks.ts
- apps/dapp/src/main.tsx
> Edit page WIP

- apps/dapp/src/components/Notification/Notification.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
* adds correct loading states for Swap
> Lbp notifications

- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
> Fix slippage

- apps/dapp/src/components/Layouts/Ascend/index.tsx
- apps/dapp/src/components/Pages/Ascend/PoolList.tsx
- apps/dapp/src/components/Pages/Ascend/admin/edit.tsx
- apps/dapp/src/components/Pages/Ascend/components/ChartInfoBar/index.tsx
- apps/dapp/src/components/Pages/Ascend/index.tsx
- apps/dapp/src/components/Pages/AscendList/index.tsx
- apps/dapp/src/hooks/ascend/index.ts
- apps/dapp/src/main.tsx
adds /ascend (list page)
adds /ascend/:pooladdress (pool page)
> Add ascend list page

- apps/dapp/package.json
- apps/dapp/src/components/Layouts/Ascend/types.ts
- apps/dapp/src/components/Pages/Ascend/components/AuctionContext/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/ChartInfoBar/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/SwapHistory/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/components/Pages/Ascend/utils.ts
- apps/dapp/src/components/Pages/AscendList/index.tsx
- apps/dapp/src/hooks/ascend/index.ts
- apps/dapp/src/utils/DecimalBigNumber.ts
> add total liquidity/paused state/manage token decimals

- apps/dapp/src/components/Pages/Ascend/index.tsx
> prevent wrong network crash

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
> fix chart ceiling

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
> fix ceiling mistake

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
> Some more chart styling

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
> change chart line color

- apps/dapp/src/components/Pages/Ascend/components/AuctionContext/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/styles.ts
> Add paused state

- apps/dapp/src/components/Layouts/Ascend/types.ts
- apps/dapp/src/components/Layouts/Ascend/utils.ts
- apps/dapp/src/components/Pages/Ascend/PoolList.tsx
- apps/dapp/src/components/Pages/Ascend/admin/edit.tsx
- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/use-pool-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/use-pool-factory.ts
- apps/dapp/src/data/abis/liquidityBootstrappingPool.json
- apps/dapp/src/hooks/ascend/index.ts
Hooking up contract calls with loading, error states in the UI.
- Create Pool
- updateWeightsGradually
- setSwapEnabled
Still pending (Future PR):
- Drain
> Add contract calls to admin page

- apps/dapp/src/constants/env/preview.tsx
> Update testnet token addresses

- apps/dapp/src/components/Layouts/Ascend/types.ts
- apps/dapp/src/components/Pages/Ascend/PoolList.tsx
- apps/dapp/src/components/Pages/Ascend/admin/edit.tsx
- apps/dapp/src/components/Pages/Ascend/components/AuctionContext/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/use-pool-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/use-pool-factory.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/components/Pages/Ascend/utils.ts
- apps/dapp/src/components/PillMenu/index.tsx
- apps/dapp/src/constants/env/index.ts
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
> Update admin UI

- apps/dapp/src/components/Layouts/CoreLayout/Account.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-contract.ts
- apps/dapp/src/constants/env/index.ts
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/hooks/use-request-state.tsx
> Admin follow ups

- apps/dapp/src/components/Pages/Ascend/components/AuctionContext/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/ChartInfoBar/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/use-pool-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/utils.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/hooks/ascend/index.ts
- apps/dapp/src/utils/balancer.ts
> Ascend follow ups

- apps/dapp/src/components/Layouts/Ascend/index.tsx
- apps/dapp/src/components/Pages/Ascend/index.tsx
- apps/dapp/src/components/Pages/AscendList/index.tsx
> handle past ascent/empty liquidity

- apps/dapp/index.html
- apps/dapp/package.json
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
- apps/dapp/src/hooks/core/use-deposit-to-vault.tsx
- apps/dapp/src/main.tsx
- apps/dapp/src/services/AnalyticsService.ts
- yarn.lock
Initial integration with posthog, https://posthog.com/docs/integrate/client/js
> Posthog integration

- apps/dapp/package.json
- apps/dapp/src/components/WagmiProvider/index.tsx
> bump wagmi

- apps/dapp/src/components/Layouts/Ascend/types.ts
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/types.ts
- apps/dapp/src/components/Pages/Ascend/components/LBPForm/utils.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-contract.ts
> Support increasing liquidity in LBP

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
> fix project price ascend

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/ChartInfoBar/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/hooks/ascend/index.ts
- apps/dapp/src/utils/DecimalBigNumber.ts
- apps/dapp/src/utils/balancer.ts
> More ascend cleanup

- apps/dapp/src/components/Pages/Core/VaultPages/Stake.tsx
- apps/dapp/src/hooks/core/types.ts
- apps/dapp/src/hooks/core/use-deposit-to-vault.tsx
- apps/dapp/src/main.tsx
Capture event moved to the success callback. Also edited the success callback to pass ticker and amount, and now pass name (vault.id) to posthog.
> Improve captureEvent

- apps/dapp/src/assets/icons/arrow-icon-no-background.svg
- apps/dapp/src/components/Pages/Ascend/components/AuctionContext/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/ChartInfoBar/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/PoolComposition/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/SwapHistory/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/styles.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/utils.ts
- apps/dapp/src/components/Pages/Ascend/index.tsx
- apps/dapp/src/components/Pages/Ascend/styles.tsx
- apps/dapp/src/hooks/ascend/index.ts
- apps/dapp/src/styles/mixins.ts
- apps/dapp/src/utils/balancer.ts
- apps/dapp/src/utils/formatter.ts
> ascend bug fixes

- apps/dapp/src/components/Pages/Ascend/components/AuctionContext/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/PoolComposition/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/components/Pages/Ascend/index.tsx
* handles disconnected wallet state in UI
> make ascend visible in disconnected state

- apps/dapp/src/constants/env/production.tsx
Update production token addresses for ascend
> Set token addresses for Ascend

- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Core/VaultPages/Stake.tsx
- apps/dapp/src/constants/events.ts
https://discord.com/channels/847178511604252741/989472996886474773/1006652918461640736
Add event for LBP swap
> Add LBP swap event

- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Claim.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Stake.tsx
- apps/dapp/src/constants/events.ts
Add other analytics events as discussed here https://docs.google.com/document/d/1uXNGixO_whpCTbYlyOt5ejvf9Sr8xRzCxzEtxexHnr8/edit?usp=sharing
> feat: Add remaining custom analytics events

- apps/core-subgraph/schema.graphql
- apps/core-subgraph/src/entities/deposit.ts
- apps/core-subgraph/src/entities/vault.ts
- apps/core-subgraph/src/entities/withdraw.ts
- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Claim.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Stake.tsx
- apps/dapp/src/constants/events.ts
Primarily to get the new analytics events into prod
> Merge stage -> main

- .github/workflows/dapp-tests.yaml
- apps/dapp/index.html
Compared to before, this change shaves about 1 minute off of the build time for this action. 😀 
Resolves https://github.com/TempleDAO/temple/issues/410
> GH Action execution time improvements

- apps/dapp/src/components/Pages/Ascend/components/LBPForm/use-pool-factory.ts
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
Moves LBPFactory contract address to env var, rather than hardcoded.
> Move LBPFactory contract to an env var

- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
Emit the event first after trade txn is successful.
> Try to fix trade events

- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
- apps/dapp/src/providers/SwapProvider.tsx
Move where we do the captureEvent call for posthog analytics.
> Fix trade analytics events

- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
- apps/dapp/src/providers/SwapProvider.tsx
> stage->main to fix analytics

- apps/dapp/src/providers/SwapProvider.tsx
> Try to fix trade events again

- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
- apps/dapp/src/providers/SwapProvider.tsx
> merge stage to main to fix analytics again

- apps/dapp/src/providers/SwapProvider.tsx
> Format big numbers

- apps/dapp/src/providers/SwapProvider.tsx
> Format big numbers in trade events

- apps/dapp/src/components/Pages/Core/Trade/constants.ts
- apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx
> Remove FEI options from Trade

- apps/dapp/src/components/Pages/Ascend/components/Chart/hooks.ts
- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
* adds the predicted curve to the ascend chart
> Ascend projection

- apps/dapp/src/components/Pages/Ascend/components/Chart/index.tsx
> Raise y-axis lower bound on ascend chart

- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
Switches which factory we use to create ascend pools. 
Fixes #538
> Update LBP Factories to use NoProtocolFee variant.

- apps/dapp/src/components/Pages/Ascend/components/ChartInfoBar/index.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-contract.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/hooks/ascend/index.ts
- apps/dapp/src/utils/formatter.ts
> use callStatic to get actual price estimate

- apps/dapp/src/components/Pages/Ascend/components/Trade/hooks/use-vault-trade-state.ts
- apps/dapp/src/components/Pages/Ascend/components/Trade/index.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Claim.tsx
I don't know why captureEvent does not work in a hook. I moved it to a success callback outside of the book.
> Fix ascend event

- apps/dapp/src/components/Pages/Ascend/components/PoolComposition/index.tsx
- apps/dapp/src/utils/formatter.ts
> Fix mobile ascend

- protocol/scripts/deploys/helpers.ts
Adds mainnet contract addresses. 
> Add mainnet zap contract addresses

- apps/dapp/src/constants/env/index.ts
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
* updates configs to use our forked version of the balancer subgraph
> use forked subgraph

- apps/core-subgraph/config/local.json
- apps/core-subgraph/src/entities/metric.ts
- apps/core-subgraph/src/entities/opsManager.ts
- apps/core-subgraph/src/mappings/opsManager.ts
- apps/core-subgraph/src/utils/constants.ts
https://discord.com/channels/847178511604252741/989472996886474773/1018867695204184205
> Attempt to fix local vault subgraph

- apps/dapp/src/components/Pages/TeamPayments.tsx
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
- apps/dapp/src/enums/team-payment.ts
- protocol/scripts/local-dapp-dev/deploy.ts
> Add support for epoch 5 payments

- apps/dapp/src/components/Pages/Core/Profile/Profile.tsx
- apps/dapp/src/components/Pages/Core/Profile/components/ProfileVaults.tsx
- apps/dapp/src/components/Pages/Core/Vault.tsx
- apps/dapp/src/components/Pages/Core/VaultContext/index.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Claim.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Stake.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Strategy.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Summary.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Timing.tsx
- apps/dapp/src/components/Vault/VaultDesktop.tsx
- apps/dapp/src/components/Vault/VaultMobile.tsx
- apps/dapp/src/components/Vault/desktop-parts/timeline/Timeline.tsx
- apps/dapp/src/components/Vault/desktop-parts/timeline/TimelineTicks.tsx
- apps/dapp/src/components/Vault/mobile-parts/Timeline.tsx
- apps/dapp/src/components/WagmiProvider/index.tsx
- apps/dapp/src/hooks/core/subgraph.tsx
- apps/dapp/src/hooks/core/use-deposit-to-vault.tsx
- apps/dapp/src/hooks/core/use-vault-balance.tsx
- apps/dapp/src/providers/AppProvider.tsx
> Move vault context higher in component tree

- apps/dapp/src/components/Apy/Apy.stories.tsx
- apps/dapp/src/components/Apy/Apy.tsx
- apps/dapp/src/components/Button/Button.tsx
- apps/dapp/src/components/Footer/Footer.tsx
- apps/dapp/src/components/Metrics/Metrics.tsx
- apps/dapp/src/components/Pages/Core/HomePage.tsx
⚠️ Gamma already approved the changes in discord FYI https://discord.com/channels/847178511604252741/949614784079343616/1027796224813842472
The UI feedback for the home page.
> UI Improvements Part 1: Home page

- apps/dapp/src/components/Pages/Ascend/index.tsx
A trivial text change to confirm operation of github action for prod release.
> test prod release process

- apps/dapp/src/components/Pages/Ascend/index.tsx
Minor copy change to test release process.
> trivial change to check prod release process

- protocol/contracts/core/VaultEarlyWithdraw.sol
- protocol/scripts/deploys/goerli/22-vault-early-withdraw.ts
- protocol/scripts/deploys/goerli/23-treasury-iv.ts
- protocol/scripts/deploys/helpers.ts
- protocol/scripts/deploys/mainnet/24-vault-early-withdraw.ts
- protocol/scripts/deploys/mainnet/25-treasury-iv.ts
- protocol/test/core/vault-early-withdraw-tests.ts
Create vault early withdraw mechanism
> Frontier wip1

- protocol/scripts/deploys/helpers.ts
- protocol/scripts/deploys/mainnet/24-epoch6-payments.ts
> Deploy Epoch6 Team Payments

- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
- apps/dapp/src/enums/team-payment.ts
- protocol/scripts/deploys/helpers.ts
- protocol/scripts/deploys/mainnet/24-epoch6-payments.ts
⚠️ Update `production.tsx` the line `teamPaymentsEpoch6` after deploying the payment contract.
> Support epoch6 payments in team-payments page

- protocol/hardhat.config.ts
- protocol/scripts/deploys/governance/contract-addresses.ts
- protocol/scripts/deploys/governance/gnosis/01-templar-nft.ts
- protocol/scripts/deploys/governance/gnosis/02-elder-election.ts
- protocol/scripts/deploys/governance/gnosis/100-transfer-ownership.ts
- protocol/scripts/deploys/governance/gnosisChiado/01-templar-nft.ts
- protocol/scripts/deploys/governance/gnosisChiado/02-elder-election.ts
- protocol/scripts/deploys/governance/gnosisChiado/100-transfer-ownership.ts
- protocol/scripts/deploys/governance/localhost/999-localhost-fork-test.ts
- protocol/scripts/deploys/governance/localhost/deploy-localhost-fork.sh
- protocol/scripts/deploys/helpers.ts
> feat: deploy scripts for gov

- apps/dapp/src/components/Metrics/Metrics.tsx
> Remove APY from homepage

- apps/dapp/src/components/Pages/TeamPayments.tsx
> Fix epoch6 payments

- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
> Update alchemy+infura keys

- apps/dapp/src/components/Layouts/CoreLayout/ConnectorPopover.tsx
This change will prompt connected wallets to sign a message confirming they agree to TempleDAO's disclaimer
Supersedes #624 due to perm issue
> feat: wallet terms of service signing

- apps/dapp/src/components/Layouts/CoreLayout/ConnectorPopover.tsx
> Stage->Main

- apps/dapp/src/components/Pages/TeamPayments.tsx
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
- apps/dapp/src/enums/team-payment.ts
- protocol/scripts/deploys/helpers.ts
- protocol/scripts/deploys/mainnet/27-epoch7-payments.ts
Just add the production contract address
> Ready for epoch7 payments

- protocol/contracts/amo/TpfAmo.sol
- protocol/contracts/amo/helpers/PoolHelper.sol
- protocol/contracts/amo/interfaces/AMO__IPoolHelper.sol
- protocol/test/amo/common.ts
- protocol/test/amo/pool-helper.ts
- protocol/test/amo/tpf-amo.ts
> feat: review feedback, test cleanup

- apps/dapp/src/components/Pages/Core/VaultPages/Summary.tsx
> Remove vAPY from vault page

- protocol/test/amo/common.ts
- protocol/test/amo/ramos.ts
> update stable deposit/math

- protocol/scripts/deploys/goerli/ramos/01-ramos-amo.ts
- protocol/scripts/deploys/goerli/ramos/02-ramos-pool-helper.ts
- protocol/scripts/deploys/helpers.ts
- protocol/scripts/deploys/mainnet/ramos/01-ramos-aura-staking.ts
- protocol/scripts/deploys/mainnet/ramos/02-ramos-amo.ts
- protocol/scripts/deploys/mainnet/ramos/03-ramos-pool-helper.ts
- protocol/scripts/deploys/mainnet/ramos/99-ramos-post-deploy.ts
> chore: deploy ramos

- protocol/contracts/amo/Ramos.sol
- protocol/scripts/deploys/mainnet/ramos/02-ramos-amo.ts
- protocol/test/amo/ramos.ts
> fix: remove unused param from ramos

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Responsive CSS

- apps/dapp/src/components/Pages/Core/NewUI/PriceChartNew.tsx
> Fix chart container for mobile

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/components/Pages/Core/NewUI/PriceChartNew.tsx
- apps/dapp/src/hooks/use-refreshable-price-metrics-ramos.tsx
> Subgraph updates

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Change RAMOS TVL to Treasury Value

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/components/Pages/Core/NewUI/PriceChartNew.tsx
> Small ui tweaks

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Update marketing copy

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Update copy, add sparkles to hero ring

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Remove BackgroundTexture

- apps/dapp/package.json
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
- apps/dapp/src/main.tsx
- yarn.lock
https://github.com/TempleDAO/temple/issues/659
> removed all remains of sentry

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Temporarily set trade button to open balancer dapp

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Fix codex link

- apps/dapp/src/components/Pages/Core/NewUI/PriceChartNew.tsx
Resolves https://github.com/TempleDAO/temple/issues/703
> Price chart bug fix

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/components/Pages/Core/NewUI/PriceChartNew.tsx
> Stage -> main for small fixes

- apps/dapp/src/components/Pages/Core/NewUI/ClaimModal.tsx
- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/hooks/core/use-vault-group-token-balance.tsx
- apps/dapp/src/hooks/core/use-withdraw-from-vault.tsx
> Initial Legacy Claim modal implementation

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Fix missing var

- apps/dapp/package.json
> Fix prepare command

- apps/dapp/src/components/Layouts/CoreLayout/Account.tsx
- apps/dapp/src/components/TransactionSettingsModal/TransactionSettingsModal.tsx
> Add disconnect button

- apps/dapp/src/providers/SwapProvider.tsx
> Fix balancer deadline miscalculated

- apps/dapp/src/components/Pages/Core/NewUI/TradeNew.tsx
> Fix 6-decimal token balance not displaying on hint

- apps/dapp/src/components/Pages/Core/NewUI/ClaimModal.tsx
> Fix width of claim modal

- apps/dapp/src/components/Pages/Core/NewUI/HomeInput.tsx
- apps/dapp/src/components/TransactionSettingsModal/TransactionPreviewModal.tsx
> Fix 6-dec tokens not being able to confirm swap

- apps/dapp/src/components/TransactionSettingsModal/TransactionPreviewModal.tsx
> Add decimals when calculating preview price ratio

- apps/dapp/src/components/TransactionSettingsModal/TransactionPreviewModal.tsx
> Add decimals when calculating preview price ratio (#724)

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Add live treasury value

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
Fixes a few issues reported here https://discord.com/channels/847178511604252741/1033132382947131484/1068307183130914979
> Misc home page fixes

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Misc home page fixes (#743)

- apps/dapp/src/components/Pages/Core/NewUI/ClaimModal.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Claim.tsx
- apps/dapp/src/hooks/core/use-withdraw-from-vault.tsx
Removed the subvault withdraw method for only earlyWithdraw. Also did some styling for the modal
Fixes #742
> Update early vault withdraw modal

- apps/dapp/src/components/Pages/Core/NewUI/ClaimModal.tsx
- apps/dapp/src/components/Pages/Core/VaultPages/Claim.tsx
- apps/dapp/src/hooks/core/use-withdraw-from-vault.tsx
* Update early vault withdraw modal
* delete log
* Remove unused imports
> Update early vault withdraw modal (#748)

- apps/dapp/src/components/WagmiProvider/index.tsx
> Add injected provider

- apps/dapp/src/components/Layouts/CoreLayout/ConnectorPopover.tsx
> Filter metamask connector

- apps/dapp/src/components/Layouts/CoreLayout/ConnectorPopover.tsx
- apps/dapp/src/components/WagmiProvider/index.tsx
> Attempt to fix wagmi issue (#751)

- apps/dapp/src/constants/env/preview.tsx
> Update WETH goerli address

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
Change learn more to claim from vaults, adjust footer
> Minor UI updates

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Add arbitrum treasury to metrics

- apps/dapp/package.json
- apps/dapp/vite.config.ts
- yarn.lock
Improves debugging experience by generating human friendly class names for styled components generated class names. These class names are analogous to the name of the component they generate.
> feat: better styled components debugging

- protocol/contracts/interfaces/core/ITempleERC20Token.sol
- protocol/contracts/interfaces/oud/IOudRedeemer.sol
- protocol/contracts/interfaces/oud/IOudToken.sol
- protocol/contracts/interfaces/templeLineOfCredit/ITempleLineOfCredit.sol
- protocol/contracts/oud/OudRedeemer.sol
- protocol/contracts/oud/OudToken.sol
- protocol/test/helpers.ts
- protocol/test/oud/oud-redeemer.ts
- protocol/test/oud/oud-token.ts
> fix: update comments/interfaces for consistency

- apps/dapp/package.json
- apps/dapp/src/providers/SwapProvider.tsx
- yarn.lock
> Update SOR typechain

- apps/dapp/package.json
- apps/dapp/src/providers/SwapProvider.tsx
- yarn.lock
* Update SOR typechain
* Remove logs
> Update SOR typechain (#773)

- apps/dapp/package.json
> Remove @balancer-labs/typechain

- apps/dapp/src/components/Pages/Core/NewUI/DefendModal.tsx
> Update Defend modal copy

- apps/dapp/src/providers/WalletProvider.tsx
> Force ensureAllowance to use 50,000 gas limit

- apps/dapp/src/hooks/core/use-token-contract-allowance.tsx
- apps/dapp/src/hooks/core/use-token-vault-proxy-allowance.tsx
> Hardcode vault token approval gas to 50k

- apps/dapp/src/hooks/core/use-token-contract-allowance.tsx
- apps/dapp/src/hooks/core/use-token-vault-proxy-allowance.tsx
> Hardcode vault token approval gas to 50k (#786)

- apps/dapp/src/components/Pages/Core/NewUI/HomeInput.tsx
- apps/dapp/src/providers/SwapProvider.tsx
Adds this caret to help clarify that DAI is clickable:
Adds singleSwap to help preserve gas for direct DAI<>TEMPLE swaps (I have tested the single swap works on mainnet)
> Add balancer singleSwap, add SVG caret to crypto Input

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Fix trade button hidden on shorter screens

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Fix trade button hidden on shorter screens (#801)

- protocol/contracts/amo/Ramos.sol
- protocol/contracts/amo/helpers/AMOCommon.sol
- protocol/contracts/amo/helpers/PoolHelper.sol
- protocol/contracts/amo/interfaces/AMO__IAuraStaking.sol
- protocol/contracts/amo/interfaces/AMO__IPoolHelper.sol
- protocol/contracts/amo/interfaces/AMO__IRamos.sol
- protocol/contracts/amo/test/goerli/RamosGoerli.sol
- protocol/contracts/v2/strategies/RamosStrategy.sol
- protocol/test/amo/pool-helper.ts
- protocol/test/amo/ramos.ts
- protocol/test/forge/v2/strategies/RamosStrategy.t.sol
> Add the RAMOS strategy

- .prettierrc
- protocol/contracts/v2/interestRate/BaseInterestRateModel.sol
- protocol/test/forge/v2/interestRate/CompoundedInterest.t.sol
- protocol/test/forge/v2/interestRate/LinearWithKinkInterestRateModel.t.sol
- Add compound interest tests
- Add linear with kink interest tests
> Temple v2 review feedback tests

- protocol/test/forge/v2/strategies/RamosStrategy.t.sol
Implement RamosStrategyTestVaultFunctions tests
> Temple v2 review feedback ramos strategy tests

- apps/dapp/src/providers/WalletProvider.tsx
> Block signer from loading if client is geoblocked

- protocol/package.json
- yarn.lock
> update solidity-coverage version to match hardhat

- .github/workflows/protocol-tests.yaml
> Upgrade foundry to fix forge tests

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardContent.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Metrics/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnPaginationControl.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-txHistory.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/index.tsx
- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/components/Pages/Core/NewUI/TLC/TLCModal.tsx
- apps/dapp/src/components/Pages/Core/components/LoaderVault/commons/LoadingText.tsx
- apps/dapp/src/hooks/api/use-react-query.ts
- apps/dapp/src/hooks/use-refreshable-treasury-metrics.tsx
- apps/dapp/src/services/MetricsService.ts
- apps/dapp/src/utils/loading-value.ts
- apps/dapp/src/utils/subgraph.ts
Add strategies history transactions table to temple dashboard v2
https://github.com/TempleDAO/temple/assets/127277105/c82409e1-322c-4df0-9e46-8c39ccf0d16b
> Fostrich dashboard table subgraph

- protocol/scripts/deploys/mainnet/v2/contract-addresses.ts
> fix: update the automation EOA addr for Ramos

- apps/dapp/src/components/Layouts/CoreLayout/WrongNetworkPopover.tsx
- apps/dapp/src/components/Pages/Ramos/admin/index.tsx
- apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
- apps/dapp/src/utils/envChainMapping.ts
- Solve various react re-rendering issues
- Show wrongNetworkModal on prod
- Add ui slippage in proportionallyAddLiq call
> fix ramos admin v2 issues

- apps/dapp/src/components/Pages/Core/NewUI/HomeInput.tsx
- apps/dapp/src/components/Pages/Ramos/admin/components/RemoveLiquidity.tsx
- apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
- apps/dapp/src/components/TransactionSettingsModal/TransactionSettingsModal.tsx
> updates ramos admin ui

- apps/dapp/src/components/Pages/Ramos/admin/helpers.ts
- apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
> fix: update add/remove liquidity logic

- apps/dapp/src/components/Pages/Ramos/admin/helpers.ts
- apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
> fix: update add/remove liquidity logic (#896)

- apps/dapp/src/assets/icons/arrow-icon-up.svg
- apps/dapp/src/components/Charts/LineChart.tsx
- apps/dapp/src/components/InputSelect/InputSelect.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/styles.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Metrics/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/PaginationControl/PageRangeSelector.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/PaginationControl/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-txHistory.ts
- apps/dapp/src/hooks/api/use-react-query.ts
- apps/dapp/src/hooks/use-range-pagination.tsx
- apps/dapp/src/utils/react-query-helpers.ts
> Pagination updates

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Metrics/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
> Misc metrics tweaks and fixes

- apps/dapp/src/assets/icons/filter-icon.svg
- apps/dapp/src/components/Checkbox/Checkbox.tsx
- apps/dapp/src/components/Checkbox/RadioCheckbox.tsx
- apps/dapp/src/components/Pages/Ascend/components/Trade/styles.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/RowFilterDropdown.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/index.tsx
- apps/dapp/src/styles/styled.d.ts
- apps/dapp/src/styles/theme.ts
> Fostrich dashboard table subgraph filter symbol

- apps/dapp/src/components/Charts/LineChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
> Split chart metric by asset

- apps/dapp/src/components/Layouts/V2Layout/Nav/NavLinks.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardContent.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Metrics/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Tlc.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-txHistory.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/index.tsx
- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Add blurbs and hide tlc

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
(https://discord.com/channels/847178511604252741/1131806977488588903/1176804015552606337)
> feat: remove some v2 metrics from chart

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
> Fostrich table cents & improve table responsiveness

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
> Ensure USD values and labels

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
> Fix env import

- apps/dapp/src/components/Pages/Ramos/admin/components/AddLiquidity.tsx
- apps/dapp/src/components/Pages/Ramos/admin/components/DepositAndStakeBpt.tsx
- apps/dapp/src/components/Pages/Ramos/admin/components/RemoveLiquidity.tsx
- apps/dapp/src/components/Pages/Ramos/admin/index.tsx
- apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
> refactor: useRamosAdmin easier to read

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Update learn more doc link

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> Revert homepage copy

- apps/dapp/src/components/Layouts/CoreLayout/Account.tsx
- apps/dapp/src/components/Layouts/V2Layout/V2Account.tsx
- apps/dapp/src/components/Layouts/V2Layout/index.tsx
- apps/dapp/src/hooks/use-geo-blocked.tsx
- apps/dapp/src/providers/WalletProvider.tsx
> Fix geoblocking

- apps/dapp/src/components/Layouts/V2Layout/index.tsx
- apps/dapp/src/components/Popover/GeoblockModal.tsx
> Create geoblock notification popup

- apps/dapp/src/components/Layouts/V2Layout/index.tsx
- apps/dapp/src/components/Popover/GeoblockModal.tsx
> Create geoblock notification popup (#933)

- .github/workflows/protocol-tests.yaml
> chore: gh workflow nvm update

- protocol/slither.db.json
> chore: slither

- apps/dapp/src/components/Pages/Core/DappPages/Legacy/UnstakeOGT.tsx
> fix: OGT claim fix

- apps/dapp/src/components/Pages/Core/DappPages/Legacy/UnstakeOGT.tsx
> fix: OGT claim fix (#960)

- apps/automation-v2/Dockerfile
> chore: update dockerfile node version

- protocol/scripts/deploys/sepolia/v2/contract-addresses.ts
Add a new multisig address for temple v2 contracts
> chore: new multisig address for temple v2 sepolia

- protocol/test/forge/v2/circuitBreaker/TempleCircuitBreakerAllUsersPerPeriod.t.sol
- protocol/test/forge/v2/templeLineOfCredit/TlcBorrow.t.sol
- protocol/test/forge/v2/templeLineOfCredit/TlcCollateral.t.sol
- protocol/test/forge/v2/templeLineOfCredit/TlcRepay.t.sol
Update tests after forge gas accuracy update in: https://github.com/foundry-rs/foundry/pull/7186
> fix: forge gas tests after upstream update to accuracy

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardConfig.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
> chore: refactor DashboardData.chartStrategyNames

- apps/automation-v2/src/config/prodnets.ts
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
> Move v2 subgraph endpoint to TempleDAO org

- apps/automation-v2/src/config/prodnets.ts
- apps/automation-v2/src/config/testnets.ts
> feat: update tlc subgraph urls

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Legacy/ClaimFromVaults.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Legacy/UnstakeOGT.tsx
- apps/dapp/src/components/Pages/Core/NewUI/HomeInput.tsx
- apps/dapp/src/components/Pages/Core/NewUI/TradeNew.tsx
> Adjust alignment and misc changes

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/Withdraw.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
> UI Changes part 2

- apps/automation-v2/src/config/prodnets.ts
> fix: solve subgraph urls

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardContent.tsx
> Update TLC blurb

- protocol/contracts/core/Exposure.sol
- protocol/contracts/core/RebasingERC20.sol
- protocol/contracts/core/Vault.sol
- protocol/test/core/exposure-tests.ts
- protocol/test/core/rebasing-erc20-testsuite.ts
- protocol/test/core/vault-early-withdraw-tests.ts
> feat: use update virtual function properly

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
* fix: consistent chart metric name formatting
* fix: strategyDailySnapshots pagination strategy
> fix:  chart label formatting and pagination strategy (#979)

- apps/dapp/src/hooks/use-geo-blocked.tsx
> feat: block users when ip-country check fails

- apps/dapp/package.json
> Correct Node version

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
> Increase gaslimit for tlc borrow

- apps/dapp/src/components/Charts/BiAxialAreaChart.tsx
#1004 fix is same as other charts, this one was buggy because it's a separate component.
> fix: chart legend overlap on mobile

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
- apps/dapp/src/utils/ethers.ts
Get an _actual_ gas estimate and use that for borrow, repay, repayall, supply, and withdraw.
> Estimate gas instead of hardcoded

- apps/dapp/vite.config.ts
> Fix flaky build

- apps/dapp/vite.config.ts
> stage -> main

- apps/dapp/vite.config.ts
> Fix walletconnect (#1024)

- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/hooks/use-refreshable-price-metrics.tsx
- apps/dapp/src/utils/subgraph.ts
> Update subgraph endpoints

- .github/workflows/protocol-tests.yaml
- protocol/contracts/fakes/templegold/TempleGoldStakingMock.sol
- protocol/contracts/interfaces/templegold/ITempleGoldStaking.sol
- protocol/contracts/templegold/SpiceAuction.sol
- protocol/contracts/templegold/TempleGoldStaking.sol
- protocol/test/forge/templegold/TempleGoldCommon.t.sol
- protocol/test/forge/templegold/TempleGoldStaking.t.sol
Over-complicated design of delegation
> Tgld audit fix i03

- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
Use public rpc url (https://eth.llamarpc.com/) in dapp
> Update rpc url to public url

- protocol/contracts/interfaces/templegold/IAuctionBase.sol
- protocol/contracts/interfaces/templegold/IDaiGoldAuction.sol
- protocol/contracts/interfaces/templegold/ISpiceAuction.sol
- protocol/contracts/interfaces/templegold/ISpiceAuctionFactory.sol
- protocol/contracts/interfaces/templegold/ITempleGold.sol
- protocol/contracts/interfaces/templegold/ITempleGoldStaking.sol
- protocol/contracts/templegold/AuctionBase.sol
- protocol/contracts/templegold/DaiGoldAuction.sol
- protocol/contracts/templegold/SpiceAuction.sol
- protocol/contracts/templegold/SpiceAuctionFactory.sol
- protocol/contracts/templegold/TempleGold.sol
- protocol/contracts/templegold/TempleGoldStaking.sol
- protocol/test/forge/templegold/DaiGoldAuction.t.sol
- protocol/test/forge/templegold/SpiceAuction.t.sol
- protocol/test/forge/templegold/SpiceAuctionFactory.t.sol
- protocol/test/forge/templegold/TempleGold.t.sol
- protocol/test/forge/templegold/TempleGoldAdmin.t.sol
- protocol/test/forge/templegold/TempleGoldCommon.t.sol
- protocol/test/forge/templegold/TempleGoldStaking.t.sol
> redemption in spice auction, test update

- protocol/contracts/fakes/templegold/TempleGoldStakingMock.sol
- protocol/contracts/interfaces/templegold/ITempleGoldStaking.sol
- protocol/contracts/templegold/TempleGoldStaking.sol
- protocol/test/forge/templegold/TempleGoldStaking.t.sol
> new staking

- yarn.lock
After https://github.com/TempleDAO/temple/pull/1049 shipped, the build time was 15 minutes. I could not reproduce locally, but thought maybe re-generating yarn.lock would help. It seems to have done the trick.
> Regenerate yarn lock

- apps/automation-v2/package.json
- apps/automation-v2/src/common/discord.ts
- apps/automation-v2/src/config/prodnets.ts
- apps/automation-v2/src/config/testnets.ts
- apps/automation-v2/src/tlc/batch-liquidate.ts
- apps/automation-v2/src/utils/ethers-exceptions.ts
- apps/automation-v2/tsconfig.json
- apps/automation-v2/yarn.lock
> fix: tlc liquidations subgraph url

- protocol/contracts/fakes/templegold/SpiceAuctionMock.sol
- protocol/contracts/fakes/templegold/TempleGoldMock.sol
- protocol/contracts/interfaces/templegold/IAuctionBase.sol
- protocol/contracts/interfaces/templegold/ISpiceAuction.sol
- protocol/contracts/interfaces/templegold/ISpiceAuctionFactory.sol
- protocol/contracts/interfaces/templegold/ITempleGold.sol
- protocol/contracts/templegold/AuctionBase.sol
- protocol/contracts/templegold/DaiGoldAuction.sol
- protocol/contracts/templegold/SpiceAuction.sol
- protocol/contracts/templegold/SpiceAuctionFactory.sol
- protocol/contracts/templegold/TempleGold.sol
- protocol/contracts/templegold/TempleGoldStaking.sol
- protocol/test/forge/templegold/DaiGoldAuction.t.sol
- protocol/test/forge/templegold/SpiceAuction.t.sol
- protocol/test/forge/templegold/SpiceAuctionFactory.t.sol
- protocol/test/forge/templegold/TempleGold.t.sol
- protocol/test/forge/templegold/TempleGoldLayerZero.t.sol
- protocol/test/forge/templegold/TempleGoldStaking.t.sol
> Redemption tests

- protocol/contracts/interfaces/templegold/IAuctionBase.sol
- protocol/contracts/interfaces/templegold/ITempleGold.sol
- protocol/contracts/templegold/TempleGold.sol
- protocol/scripts/deploys/arbitrumOne/contract-addresses.ts
- protocol/scripts/deploys/localhost/templegold/01-localhost.ts
- protocol/scripts/deploys/localhost/templegold/999-localhost.ts
- protocol/scripts/deploys/localhost/templegold/deploy-anvil.sh
- protocol/test/forge/templegold/TempleGoldAdmin.t.sol
> deploy script, anvil, cleanup

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
> stage->main updating MAX_LTV

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardConfig.tsx
> Update fohmo description text

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/Repay.tsx
> Ux feedback - max should not exceed dai balance

- apps/dapp/package.json
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/Chart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-txHistory.ts
- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
- apps/dapp/src/utils/subgraph.ts
- apps/dapp/yarn.lock
> feat: update subgraph api to use zod with retries

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/Borrow.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
Adds the new outstanding user debt.
Resolves #1114
> Add outstanding user debt

- apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/Borrow.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/TLC/Withdraw.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
> fix: TLC available to borrow

- .github/workflows/protocol-deep-invarianats.yaml
- .github/workflows/protocol-tests.yaml
> foundry stable

- .github/workflows/protocol-deep-invarianats.yaml
- .github/workflows/protocol-tests.yaml
- protocol/contracts/interfaces/templegold/IStableGoldAuction.sol
- protocol/contracts/templegold/StableGoldAuction.sol
- protocol/test/forge/unit/templegold/StableGoldAuction.t.sol
> Auction update

- apps/dapp/src/components/Layouts/V2Layout/index.tsx
- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/main.tsx
> Unhide for launch

- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/hooks/spicebazaar/use-auction-countdown.tsx
> Fix subgraph url and tweak countdown logic

- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Earn/Auctions/index.tsx
- apps/dapp/src/providers/SpiceBazaarProvider.tsx
- apps/dapp/src/providers/WalletProvider.tsx
> Fix total epoch rewards

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardConfig.tsx
- apps/dapp/src/constants/env/local.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/constants/env/production.tsx
- apps/dapp/src/constants/env/types.ts
> feat: add cosecha segunda to dashboard

- apps/dapp/src/providers/SpiceBazaarProvider.tsx
> Fix daily vest calculation

- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Earn/Auctions/index.tsx
- apps/dapp/src/components/Web3OnboardInitProvider/index.tsx
> Fix USDS price ratio display and walletconnect

- .github/workflows/protocol-deep-invarianats.yaml
- .github/workflows/protocol-tests.yaml
- protocol/foundry.toml
- protocol/yarn.lock
> feat: update foundry config

- apps/dapp/src/components/Pages/Core/NewUI/Home.tsx
- apps/dapp/src/hooks/use-temple-price.tsx
> Use new endpoint for temple price

- protocol/scripts/deploys/arbitrumSepolia/constants.ts
- protocol/scripts/deploys/arbitrumSepolia/templegold/99a-post-deploy.ts
- protocol/scripts/deploys/berachain/constants.ts
- protocol/scripts/deploys/berachain/templegold/01-tgld.ts
- protocol/scripts/deploys/berachain/templegold/99-post-temple-gold.ts
- protocol/scripts/deploys/berachain/templegold/99-post-transfer-ownership.ts
- protocol/scripts/deploys/mainnet/constants.ts
- protocol/scripts/deploys/mainnet/templegold/99a-post-temple-gold.ts
- protocol/scripts/deploys/mainnet/templegold/contract-addresses.ts
- protocol/scripts/deploys/sepolia/constants.ts
- protocol/scripts/deploys/sepolia/templegold/99-post-deploy.ts
> enforced options

- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Bid/Chart/Chart2.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Bid/hooks/use-stableGold-auction-metrics.ts
> Fix tgld auction chart dates

- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Bid/Chart/Chart2.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Bid/hooks/use-stableGold-auction-metrics.ts
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Spend/BidTGLD.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Spend/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/components/GetYAxisDomainAndTicks.ts
- apps/dapp/src/utils/subgraph.ts
Address various feedback:
- Move bridge section
- Slightly tweak bid screen text
- Add new metrics dropdown to TGLD auction history chart
> Changes to TGLD auction chart and other feedback

- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardContent.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts
- apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
The Shutdown strategies either error or render in a sub-optimal way.
E.g. Before:
After:
Same applies to Ramos.
Fixes #1190
> Fix Base DSR dashboard shutdown strategies bug

- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Bid/hooks/use-auctions-history.ts
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Earn/StakeTemple/Delegate.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Earn/StakeTemple/index.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/MyActivity/BidsForSpice/hooks/use-myActivity-bidsSpiceHistory.ts
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/MyActivity/BidsForTGLD/hooks/use-myActivity-bidsTGLDHistory.ts
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Spend/BidTGLD.tsx
- apps/dapp/src/components/Pages/Core/DappPages/SpiceBazaar/Spend/Table/DataTable.tsx
- apps/dapp/src/constants/env/preview.tsx
- apps/dapp/src/main.tsx
- apps/dapp/src/providers/SpiceBazaarProvider.tsx
- Introduces new Delegation from the Figma design
- A few misc fixes for Spice Bazaar features
> Add Delegation page
