apps/dapp/src/components/Pages/Core/Profile/Profile.tsx
* removes the Temple Earned stat on the profile page, which has been confusing for users.
=> Remove earned stat

apps/core-subgraph/schema.graphql, apps/core-subgraph/src/entities/deposit.ts, apps/core-subgraph/src/entities/vault.ts, apps/core-subgraph/src/entities/withdraw.ts
Replacing the daily snapshots - hourly snapshots provide more accuracy.
=> Add hourly snapshots for Vaults data to subgraph

apps/dapp/src/components/Pages/Core/Trade/constants.ts
When first switching to selling $TEMPLE, $FRAX isn't always show as an option in the input select. This was being caused by _INITIAL_STATE_ defaulting _isFraxSellDisabled_ to false, causing the [_buildSelectConfig_ ](https://github.com/TempleDAO/temple/blob/stage/apps/dapp/src/components/Pages/Core/Trade/utils.ts#L32-L37)to render only the $FEI ticker rather than a select. 
Fixes #475
=> Change INITIAL_STATE of isFraxSellDisabled from true to false

apps/dapp/src/providers/StakingProvider.tsx
* removes some legacy/unneeded contract calls related to the exit queue to unbreak unstaking
Fixes #523
=> Remove exit queue calls from unstaking

.vercelignore
API deployments currently broken because the apps/api directory is ignored by vercel. This PR un-ignores it.
=> Fix vercel api deployments

.github/workflows/sync-typechain-dirs.yaml
Whenever there is a change in the contracts we have to generate new typechain files. This github action automates that whenever a PR is sucessfully merged that changes anything in `protocol/contracts/**`
Fixes #271 
- We have to use `yarn compile` and generate the files in the container that the GH Action runs in because `protocol/typechain` is in .gitignore and doesn't get included in the container when it spins up
- You can check/open a PR to see the GH Action working on my [fork](https://github.com/BoxedFruits/temple-dev/pull/25). [Link to my actions dashboard](https://github.com/BoxedFruits/temple-dev/actions/runs/2943020524)
=> Create new github action to sync typechain directories

apps/dapp/src/components/Pages/Ramos/admin/components/AddLiquidity.tsx, apps/dapp/src/components/Pages/Ramos/admin/components/RemoveLiquidity.tsx, apps/dapp/src/components/Pages/Ramos/admin/index.tsx, apps/dapp/src/components/Pages/Ramos/admin/styles.ts, apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
Fixes AddLiquidity on the RAMOS admin screen by 
- Only allowing user to enter stable amount
- Auto-calculating TEMPLE amount based on temple/stable ratio
Also addresses requests: 
- Adds a link to RAMOS contract etherscan 
- Adds description of add/remove liquidity 
=> Ramos addliquidity update

apps/dapp/src/components/Pages/Ramos/admin/useRamosAdmin.ts
contains:
fix: addliquidity calculation (#728)
=> stage > main

apps/dapp/src/components/Pages/Core/Trade/constants.ts, apps/dapp/src/components/Pages/Core/Trade/use-swap-controller.tsx, apps/dapp/src/constants/env/local.tsx, apps/dapp/src/constants/env/preview.tsx, apps/dapp/src/constants/env/production.tsx, apps/dapp/src/constants/env/types.ts, apps/dapp/src/enums/ticker-symbol.ts, apps/dapp/src/providers/SwapProvider.tsx, apps/dapp/src/providers/WalletProvider.tsx, apps/dapp/src/providers/types.ts, apps/dapp/src/utils/bigNumber.ts
=> Add ETH and WETH to swap options

apps/dapp/src/components/Pages/Core/NewUI/ClaimModal.tsx, apps/dapp/src/components/Pages/Core/NewUI/UnstakeModal.tsx, protocol/scripts/local-dapp-dev/deploy.ts
Fixes #749 
Users will first see Unlock prompt if they have locked OGT
Then they will see the unstake prompt
=> Add OGT unlocking to unstake modal

protocol/contracts/common/CommonEventsAndErrors.sol, protocol/contracts/interfaces/v2/ITreasuryReservesVault.sol, protocol/contracts/interfaces/v2/strategies/ITempleStrategy.sol, protocol/contracts/v2/TempleDebtToken.sol, protocol/contracts/v2/TreasuryReservesVault.sol, protocol/contracts/v2/interestRate/CompoundedInterest.sol, protocol/contracts/v2/safeGuards/SafeForked.sol, protocol/contracts/v2/safeGuards/ThresholdSafeGuard.sol, protocol/contracts/v2/strategies/AbstractStrategy.sol, protocol/contracts/v2/strategies/DsrBaseStrategy.sol, protocol/contracts/v2/strategies/GnosisStrategy.sol, protocol/test/forge/v2/TempleDebtToken.t.sol, protocol/test/forge/v2/strategies/AbstractStrategy.t.sol, protocol/test/forge/v2/strategies/DsrBaseStrategy.t.sol, protocol/test/forge/v2/strategies/GnosisStrategy.t.sol
=> TLC pre-requisites

apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/index.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/index.tsx, apps/dapp/src/hooks/api/use-react-query.ts
Store selected chart/metric in url param so we can link to specific dashboards.
Preserves selected option when switching dashboards
https://github.com/TempleDAO/temple/assets/8642344/0eff4ce9-2645-412c-ac9d-deb4a4e750a5
=> Store dashboard chart type in URL and Daily chart data

apps/dapp/src/components/Charts/BiAxialAreaChart.tsx, apps/dapp/src/components/Charts/LineChart.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx
Split chart tooltip `metric: value` to two lines when on mobile
=> fix: split chart tooltip on two lines on mobile

.github/workflows/tasks-docker-image.yml, apps/automation-v2/package.json, apps/automation-v2/src/config/prodnets.ts, apps/automation-v2/src/config/testnets.ts, apps/automation-v2/src/subgraph/subgraph-request.ts, apps/automation-v2/src/tlc/batch-liquidate.ts, apps/automation-v2/yarn.lock
<details>
<summary>Example of wrong `thegraph` and wrong `alchemy` endpoints</summary>
[2023-11-30T05:54:50.917Z] info: tlc-batch-liquidate-wh: attached at endpoint: /webhooks/tlc-batch-liquidate-wh {}
[2023-11-30T05:54:50.935Z] info: tlc-batch-liquidate scheduled - first run at 2023-11-30T06:00:00.000Z {}
[2023-11-30T05:54:50.935Z] info: waiting to run tlc-batch-liquidate at 2023-11-30T06:00:00.000Z {}
[2023-11-30T05:54:50.936Z] info: http server running on port 8111 {}
[2023-11-30T05:54:51.719Z] info: http: ["POST","/webhooks/tlc-batch-liquidate-wh"] {}
[2023-11-30T05:54:51.720Z] info: starting task action tlc-batch-liquidate-wh {"task_type":"tlc-batch-liquidate-wh","taskId":"T-1"}
[2023-11-30T05:54:51.748Z] info: try axios post to: 
{ "subgraphUrl": …
=> feat: add exponential backoff retries & fallback to alchemy api 

apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts, apps/dapp/src/components/Pages/Core/NewUI/Home.tsx, apps/dapp/src/constants/env/local.tsx, apps/dapp/src/constants/env/preview.tsx, apps/dapp/src/constants/env/production.tsx, apps/dapp/src/constants/env/types.ts
=> Use updated templeCirculatingSupply

apps/dapp/src/components/Layouts/CoreLayout/Account.tsx, apps/dapp/src/components/Layouts/V2Layout/Nav/WalletNav.tsx, apps/dapp/src/components/Layouts/V2Layout/V2Account.tsx, apps/dapp/src/components/Layouts/V2Layout/index.tsx, apps/dapp/src/components/Pages/Core/DappPages/Legacy/ClaimFromVaults.tsx, apps/dapp/src/components/Pages/Core/DappPages/Legacy/UnstakeOGT.tsx, apps/dapp/src/components/Pages/Core/NewUI/TradeNew.tsx, apps/dapp/src/hooks/use-geo-blocked.tsx, apps/dapp/src/providers/WalletProvider.tsx
Instead of preventing geoblocked users from connecting their wallet, this PR intends to limit which pages are accessible, so that only the legacy withdraw functionality is permitted.
=> Limit geoblocked users to legacy withdraw page

apps/dapp/src/components/Pages/Core/DappPages/Legacy/ClaimFromVaults.tsx
1/ changed the approval from the exact subvault balance to MaxUint256 (we were losing decimal place precision before)
2/ stopped using the wagmi allowance hook in exchange for a more verbose ethers approval flow. basically the same approval flow from Ohmage OTC, which could eventually be abstracted
=> fix: vault claim approval rounding err

apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts
Due to recent changes to the v2 subgraph, we have to get the Temple spot price from the Ramos subgraph.
=> Use Ramos subgraph to get Temple spot price

apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardConfig.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-txHistory.ts, apps/dapp/src/utils/react-query-helpers.ts
Responding to the feedback from https://github.com/TempleDAO/temple/pull/980#discussion_r1513068442 , I took the following approach:
- Remove ALL and TREASURY_RESERVES_VAULT StrategyKeys
- Added a special TRV_KEY and type instead of an `undefined` (this to me is better than using undefined)
- Add isTRVStrategy helper method to consolidate logic and keep a separation of concerns.
=> Remove ALL and TRV strategy keys

apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/V2StrategyMetricsChart.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Chart/index.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardConfig.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/DashboardContent.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Metrics/index.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnHistoryTable.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/index.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-daily-snapshots.ts, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-metrics.ts, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/hooks/use-dashboardv2-txHistory.ts, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/index.tsx, apps/dapp/src/utils/react-query-helpers.ts
This is a refactor motivated by previous [pain](https://github.com/TempleDAO/temple/pull/954) we experienced when adding a new strategy to the Dashboard.
The approach is basically to centralize all the dashboard data, and pass the selected dashboard data around from the root level. Anywhere we multiple copies of the same thing based on each dashboard (e.g. navlinks, "react query" queries for metrics, etc) we do that dynamically.
In the end, we should only have to edit a single file when updating strategies on the Dashboard. (DashboardConfig.tsx)
=> chore: Refactor dashboard configuration to one place

protocol/contracts/fakes/templegold/TempleGoldMock.sol, protocol/contracts/templegold/TempleGold.sol, protocol/test/forge/templegold/TempleGoldLayerZero.t.sol
Configuring compose option will prevent users from receiving TGLD on the destination chain
Users are able to send their TGLD by calling send function of TempleGold contract.
Since SendParam struct is passed from users, they can add any field including compose data into the message.
However on the destination chain, in _lzReceive function, it blocks messages with compose options in it:
```if (_message.isComposed()) { revert CannotCompose(); }```
This means that users who call send with compose option, they will not receive TGLD tokens on the destination chain.
It has Medium severity because token transfer does not work based on the parameter and causes loss of funds for users.
1. In send function, if the _sendParam includes compose option, it should revert.
2. Even better, send function …
=> tgld audit fix m04

protocol/contracts/interfaces/templegold/IAuctionBase.sol, protocol/contracts/interfaces/templegold/ISpiceAuction.sol, protocol/contracts/templegold/DaiGoldAuction.sol, protocol/test/forge/templegold/DaiGoldAuction.t.sol, protocol/test/forge/templegold/SpiceAuction.t.sol
When recoverToken in DaiGoldAction contract is called, it does not update the status
recoverToken function moves specific amount of TGLD from the auction contract to another and delete last epoch so that it can be reset and restart.
The tokens get moved but the status nextAuctionGoldAmount is not subtracted, and this gives incorrect amount of TLGD tokens to the next epoch, and as a result, the bidders won't be able to claim their TGLD.
The nextAuctionGoldAmount should be subtracted when tokens are moved in recoverToken function.
tgld audit fix m02
- `nextAuctionGoldAmount` should be updated by addition of leftover amounts instead of subtracting. `nextAuctionGoldAmount` is set to zero in `startAuction`. Also there can be distribution of TGLD after auction start. Added tests to support …
=> tgld audit fix m02

protocol/contracts/templegold/SpiceAuction.sol, protocol/test/forge/templegold/SpiceAuction.t.sol
Incorrect end time setting for spice auction
In startAuction function of SpiceAuction contract, the end time is set wrong.
```
uint128 startTime = info.startTime = uint128(block.timestamp) + config.startCooldown;
uint128 endTime = info.endTime = uint128(block.timestamp) + config.duration;
```
Currently, endTime is set using block.timestamp, not startTime calculated above.
It has Medium severity
endTime should be calculated using startTime and duration
```
uint128 endTime = info.endTime = startTime + config.duration;
```
tgld audit fix m07
=> tgld audit fix m07

protocol/contracts/templegold/TempleGoldStaking.sol, protocol/test/forge/templegold/TempleGoldStaking.t.sol
Users can't unset vote delegation after the delegate reset self delegation
If A sets B as its delegate, _delegateBalances is increased by A's balance.
When B reset self delegation, its _delegateBalances becomes zero.
However when A unsets its delegation from B, it tries to decrease B's _delegateBalances by A's balance.
```solidity
// TempleGoldStaking.sol:L195
if (userBalance > 0) {
// update vote weight of old delegate
uint256 _prevBalance = _delegateBalances[_delegate];
uint256 _newDelegateBalance = _delegateBalances[_delegate] = _prevBalance - userBalance;
_updateAccountWeight(_delegate, _prevBalance, _newDelegateBalance, false);
}
```
This reverts because _prevBalance is already zero.
As a result A won't be able to unset its delegation from B.
This also happens in withdrawal and stake …
=> tgld audit fix m10

protocol/contracts/templegold/TempleGoldStaking.sol, protocol/test/forge/templegold/TempleGoldStaking.t.sol
In staking contract, resetting self delegation will reset vote weight to zero
In TempleGoldStaking contract, when a delegate resets self delegation, the vote weights delegated to the delegate will be removed by calling _updateAccountWeight.
Since zero is passed as new balance parameter, the stakingTime of vote weight is reset to zero:
// TempleGoldStaking.sol:L580
```solidity
if (_newBalance == 0) {
t = 0;
_lastShares = 0;
}
```
This means that the delegate's vote weight starts accumulating from zero even though the delegate has their own balance, which should not be decreased.
It has Medium severity because the delegate loses voting power, even becoming zero if resetting self delegation happens right before an epoch ends.
When resetting self delegation, it should not decrease stakeTime …
=> tgld audit fix m06

protocol/contracts/templegold/TempleGoldStaking.sol, protocol/test/forge/templegold/TempleGoldStaking.t.sol
In setUserVoteDelegate function, when a user set vote delegator to himeself, his _delegateBalances value doesn't contain his userBalance from L149.
When he changes vote delegator from himself to another user, it subtracts userBalance from _delegateBalances from L145. But it shouldn't subtract userBalance.
```solidity
File: contracts\templegold\TempleGoldStaking.sol
136:         if (userBalance > 0) {
137:             uint256 _prevBalance;
138:             uint256 _newDelegateBalance;
139:             if (removed) {
140:                 // update vote weight of old delegate
141:                 _prevBalance = _delegateBalances[_userDelegate];
142:                 /// @dev skip for a previous delegate with 0 users delegated and 0 own vote weight
143:                 if (_prevBalance > 0) { …
```
=> tgld audit fix m13

protocol/contracts/interfaces/templegold/ITempleGoldStaking.sol, protocol/contracts/templegold/TempleGoldStaking.sol, protocol/test/forge/templegold/TempleGoldStaking.t.sol
The TempleGoldStaking.sol contract is a fork of the Synthetix rewards distribution contract, with slight modifications. The code special-cases the scenario where there are no users, by not updating the cumulative rate when the _totalSupply is zero, but it does not include such a condition for the tracking of the timestamp from L476.
```solidity
File: contracts\templegold\TempleGoldStaking.sol
475:     function _rewardPerToken() internal view returns (uint256) {
476:         if (totalSupply == 0) {
477:             return rewardData.rewardPerTokenStored;
478:         }
479: 
480:         return
481:             rewardData.rewardPerTokenStored +
482:             (((_lastTimeRewardApplicable(rewardData.periodFinish) -
483:                 rewardData.lastUpdateTime) *
484: …
```
=> tgld audit fix m12

protocol/contracts/interfaces/templegold/ITempleGoldStaking.sol, protocol/contracts/templegold/TempleGoldStaking.sol, protocol/test/forge/templegold/TempleGoldStaking.t.sol
When a staker delegates his balance to a delegator, the time duration variable _weights[delegate].stakeTime is decreased. However, when undelegating only the balance is decreased. This makes it possible a malicious user can decrease _weights[delegate].stakeTime. He can expand the impact of this attack by repeating delegating and undelegating.
A malicious user can delay the increase of any delegator's voteWeight as much as he wants.
The mechanism for adjusting the stakingTime between delegation and undelegation should be improved.
Regarding the recommendation, not sure what would be a good solution to prevent repetition of delegation and undelegation to decrease `stakeTime`
tgld aucit fix h15
=> tgld audit fix h15

apps/dapp/.eslintrc, apps/dapp/package.json, apps/dapp/src/components/Layouts/Ascend/PillMenu/index.tsx, apps/dapp/src/components/Layouts/V2Layout/Footer.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Metrics/index.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/PaginationControl/PageRangeSelector.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/RowFilterDropdown.tsx, apps/dapp/src/components/Pages/Core/DappPages/Dashboard/Table/TxnDataTable.tsx, apps/dapp/src/components/Pages/Core/NewUI/Home.tsx, apps/dapp/src/components/Pages/Safe/admin/SafeTxDataTable.tsx
This PR adds the no-array-index-key lint rule, closing the last of the items in #904.
There are a couple places I added `eslint-disable-next-line react/no-array-index-key` because I didn't think it was worth it to try to implement some convoluted key based on the existing data (e.g. rows of metrics). Happy to change if the reviewer think it's worth it.
=> Add no-array-index-key eslint rule

apps/dapp/src/components/Pages/Core/DappPages/Borrow/index.tsx
With new TPI calculations, we need to round the TPI to 2 decimal places for display in the dapp.
=> Round TPI to 2 decimal places on borrow page
